### PR TITLE
Add ntpTimeSync in Watchy.cpp

### PR DESCRIPTION
**Pull request by etwasmitbaum**
Thanks to @schodet here is the ntpTimeSync added to the Watchy.cpp file, so it will work no matter which Watch Face you use.

With this ntpTimeSync function the time will be synced from the Internet when connected to Wi-Fi.
The interval for these updates can be set in the config.h file.
The "ntpTimeSync()" Code was provided by @OverThinker.

Co-Authored-By: OverThinker <4897304+OverThinker@users.noreply.github.com>

### CODE REVIEW

**Comment by etwasmitbaum** [comment]
Has anyone else than me tested this code? 
My Time is going a few minutes faster than the actual time while using this, even though It syncs the time every hour.

**Comment by schodet** [comment]
I am trying it right now.

What do you mean by a few minutes faster?

**Comment by etwasmitbaum** [comment]
I am sorry if I wasn't clear. 
What I ment is that the actual time is 10:30 but my Watchy shows 10:35.

**Comment by schodet** [comment]
For the moment it is running fine here, are you sure it is not just RTC drift?

**Comment by etwasmitbaum** [comment]
My RTC dirfts pretty hard but even after making the a ntpTimeSync the the time is not adjusted to the correct time.
For example:
Actual time: 10:50
Watchy time: 10:55
*syncing time at 11:00*
Actual time 11:01
Watchy time 11:07

**Comment by schodet** [comment]
OK, that’s weird :)
Someone is having the same problem right now on discord

**Comment by therealmitchconnors** [comment]
I did not know someone was working on this issue, and published #71 , which adds ntp sync during init() and getWeather() calls to avoid activating wifi more than necessary. One other difference is that I get the offset from ip-api.com, rather than having it hard coded.   I'm not sure which approach is preferable, but we definitely shouldn't merge both.  

Sorry for duplication of effort.

**Comment by silmaril42** [comment]
I integrated this code into my project and NTP works fine :+1: 

Some things I think could be improved:
 - Move the configuration to `config.h`
 - Remember last successful sync time and try to sync if this is older than the interval and Wifi is connected. This way the time will be updated as soon as the watch enters it's Wifi after being away for some time.
   - I also like @therealmitchconnors idea of coupling the sync action to the weather update, but I still wouldn't do the NTP sync every half hour.
 - The decision to apply DST should be made based on the current date and configurable DST start and end dates. Otherwise users would need a "summer build" and a "winter build".

I'll just leave those ideas here, because I probably won't find the time to implement them in the near future, but maybe someone else is up to it?

**Comment by etwasmitbaum** [comment]
@silmaril42 I made the changes you requested and pushed them here. Let me know if this is what you had in mind.
>The decision to apply DST should be made based on the current date and configurable DST start and end dates. Otherwise users would need a "summer build" and a "winter build".

I am not sure how the set 'DAYLIGHT_OFFSET_SEC' works but I think, if this is set, you don't need to adjust the time yourself to winter and summer time.

**Comment by silmaril42** [comment]
> Has anyone else than me tested this code?
> My Time is going a few minutes faster than the actual time while using this, even though It syncs the time every hour.

Yes, I can confirm this. I tested with two different Watchy devices. NTP sync works fine, but there was a 5 minute offset within 2 hours, which increased to 9 minutes within a day.

I did not watch the time closely at 8:00, 16:00 or 0:00, when sync occurs, so I cannot say if the sync changes the offset back to zero (which would mean, NTPsync is working fine, but the watch itself is running much too fast).

**Comment by schodet** [comment]
`configTime` actually calls lwip `sntp_init` which initialize the NTP client and sends the first request. The first time `getLocalTime` is called, there is a hack to wait until the year is greater than 2016, but the next times, the year is set yet so it does not wait and the code stops wifi before the reply can be received.

`sntp_init`: http://git.savannah.nongnu.org/cgit/lwip.git/tree/src/apps/sntp/sntp.c#n672

So actually it seems that there is no update after the first sync.

**Comment by etwasmitbaum** [comment]
>and the code stops wifi before the reply can be received.

Could adding a `delay` of a few seconds right after `configTime` fix this issue?

**Comment by schodet** [comment]
Not very elegant, but yes I suppose it could work.

**Comment by etwasmitbaum** [comment]
I will close this PR since I am very busy right now and have no time to resolve the conflicts

**Pull request closed without merging**
