### PR TITLE
if wifi is not configured do not display weather

### PR DESCRIPTION
**Pull request by denics**
ATM if wifi is not configured random numbers are displayed instead of ... well, nothing :)

### CODE REVIEW

**Comment by sqfmi** [comment]
Currently if no connected to WiFi, it reports the [internal temperature sensor](https://github.com/sqfmi/Watchy/blob/342eb48a497eb3dcb1ec03c5c156937fdec07ba9/src/Watchy.cpp#L671). I'm going to push an update to show a microchip icon to indicate that, instead of the current code which defaults to the sunny icon.

**Comment by wjgeorge** [comment]
aren't we supposed to merge into dev first, this patch is targeted to master

**Comment by sqfmi** [comment]
Yes please target the PRs for the dev branch

**Comment by denics** [comment]
Sorry, I did not realize when I pushed. I will make also a change, instead of removing the temperature, I will display a "cpu" icon indicating that we are using the internal temperature

**Comment by sqfmi** [comment]
Thanks @denics, that update should be on the dev branch now, check it out and let us know :)

**Pull request closed without merging**
