### PR TITLE
add arduino_pins.h

### PR DESCRIPTION
**Pull request by tbjers**
- switch to ArduinoJSON
- include arduino_pins.h from config.h

### CODE REVIEW

**Comment by Swepedia** [comment]
Recently got my Watchy and ended up testing this code to get the battery display working. Seems to work just fine, just had to install the ArduinoJson library.

**Comment by sqfmi** [comment]
Thanks for this fix! Looking to merge the pins definition change. Can we keep the update to ArduinoJSON in a separate PR? Any feedback on this library if it is better (i.e. performance, APIs, size, etc.)?

**Comment by tbjers** [comment]
@sqfmi I elected to switch to ArduinoJson because it is an actively developed library, with a larger community behind it. It also offers better error and memory handling.

https://arduinojson.org/

Compare that to Arduino_JSON which hasn't been touched in a year.

**Comment by synthead** [comment]
> Thanks for this fix! Looking to merge the pins definition change. Can we keep the update to ArduinoJSON in a separate PR? Any feedback on this library if it is better (i.e. performance, APIs, size, etc.)?

I greatly second this.  I understand that `ArduinoJSON` has its advantages, but it has nothing to do with changing pins.

**Comment by tbjers** [comment]
> > Thanks for this fix! Looking to merge the pins definition change. Can we keep the update to ArduinoJSON in a separate PR? Any feedback on this library if it is better (i.e. performance, APIs, size, etc.)?
> 
> I greatly second this. I understand that ArduinoJSON has its advantages, but it has nothing to do with changing pins. Plus, there are opportunities to introduce bugs and unexpected behavior with making larger changes than necessary.

Thank you for the feedback! I will adjust this tomorrow and get you a cleaner PR.

**Comment by ITCactus** [comment]
@tbjers this will broke other hearts, if this will be merged :)
somehow, i have version 1.5, but your changes makes v2.0 pins by default.
so for me, this will make the watchy unusable.

i realized, that to make my watchy unit works properly after the flashing a watchface in ArduinoIDE, i have to change "config.h" in the arduino libraries (e.g. in "Arduino\libraries\Watchy\src\config.h") and try to play with "ARDUINO_WATCHY_Vxx" define.
for me, i had to set [on line 17](https://github.com/sqfmi/Watchy/blob/master/src/config.h#L17)
`#define ARDUINO_WATCHY_V15`
to make it work with my unit.
not sure where the "ARDUINO_WATCHY_Vxx" is supposed to be properly defined...

by default, it will be v2.0, like your changes in "arduino_pins.h"

**Comment by tlhintoq** [comment]
Brandy new watchy 29jul2022
Trying to follow what's the current state of this.

Maybe I'm just a dumb C# coder but... If this was figured out back in April... Then it would have been nice if a new July shipment didn't still have this bug.  I mean, would have been nice if out of the box the default UI (7-seg) reported the battery state.

**Comment by tbjers** [comment]
> i realized, that to make my watchy unit works properly after the flashing a watchface in ArduinoIDE, i have to change "config.h" in the arduino libraries (e.g. in "Arduino\libraries\Watchy\src\config.h") and try to play with "ARDUINO_WATCHY_Vxx" define.
> for me, i had to set [on line 17](https://github.com/sqfmi/Watchy/blob/master/src/config.h#L17)
> `#define ARDUINO_WATCHY_V15`
> to make it work with my unit.
> not sure where the "ARDUINO_WATCHY_Vxx" is supposed to be properly defined...

I think this is something that should be covered in the README file, what do you think? Sounded fairly easy to address by just changing the define, right?

**Comment by tbjers** [comment]
Since this has already been merged in #162 this can now be closed.

**Comment by ITCactus** [comment]
> Brandy new watchy 29jul2022 Trying to follow what's the current state of this.
> 
> Maybe I'm just a dumb C# coder but... If this was figured out back in April... Then it would have been nice if a new July shipment didn't still have this bug. I mean, would have been nice if out of the box the default UI (7-seg) reported the battery state.

i also have a fresh watchy, from mouser. and it supposed to work without any issues... 
but than i discovered, there are 3 hardware revisions of the watchy.... and while the first one can be distinguished by the RTC type, the 1.5 version and 2.0 are not at all. there is no single mark on the package or even on the circuit board at all! you have to flash it by yourself just to discover you got some issues, and search for any solutions... and it's not even described in the ["Getting Started" guide](https://watchy.sqfmi.com/docs/getting-started)... 
probably, it's a part of the fun you have to get from this riddle, isn't @sqfmi? :)

**Comment by PThibodeau** [comment]
Just received my new Watchy today and I'm having the same issue out of the box. I'll try this PR change and see if it fixes my issue.

**Comment by PThibodeau** [comment]
> > Just received my new Watchy today and I'm having the same issue out of the box. I'll try this PR change and see if it fixes my issue.
> 
> you don't have, because if the latest watchy release doesn't work for you, that's make no sense... look at [my comment](https://github.com/sqfmi/Watchy/pull/150#issuecomment-1180247865) most probably you have hardware revision 1.5.

Wouldn't upgrading to the latest version resolve this, since this PR was merged? It says I'm on v1.3.3

**Comment by tlhintoq** [comment]
> > Just received my new Watchy today and I'm having the same issue out of the box. I'll try this PR change and see if it fixes my issue.
> 
> you don't have, because if the latest watchy release doesn't work for you, that's make no sense... look at [my comment](https://github.com/sqfmi/Watchy/pull/150#issuecomment-1180247865) most probably you have hardware revision 1.5.

Well... 22 days ago latest watchy still did it, as I posted then.  You can say it makes no sense - and I agree with you - that it makes no sense that the latest and current shipping product doesn't work out of the box - really put me off of this entire thing to be honest.  Haven't bothered to work with it since.

**Comment by PThibodeau** [comment]
> as i already [mentioned](https://github.com/sqfmi/Watchy/pull/150#issuecomment-1200145347)
> 
> > there are 3 hardware revisions of the watchy.... and while the first one can be distinguished by the RTC type, the 1.5 version and 2.0 are not at all. there is no single mark on the package or even on the circuit board at all! you have to flash it by yourself just to discover you got some issues, and search for any solutions... and it's not even described in the ["Getting Started" guide](https://watchy.sqfmi.com/docs/getting-started)...
> 
> so, in sum, if your watchy revision is NOT 2.0, you will have to play with "config.h"
> 
> > for me, i had to set [on line 17](https://github.com/sqfmi/Watchy/blob/master/src/config.h#L17)
> > #define ARDUINO_WATCHY_V15
> > to make it work with my unit.
> 
> @tbjers, @PThibodeau most probably you will need to do the same. no update will fix your case, because from what i see, [this commit](https://github.com/sqfmi/Watchy/commit/170029672a2bd4d3a9cbf72d2e640beb94e7d138#diff-c24f78b3519d763901eb9f67b864f01d802d803df1b24faaf154019cf812bf95R20) from May 4 added "defaults" for the hardware revision 2.0. and according to [this comment](https://github.com/sqfmi/Watchy/commit/4b739afbd0042db2f7704eae16430b74da672658#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R20) from May 7, @sqfmi assumes that "Watchy v2.0" (if purchased in 2022)". not sure why. maybe mouser sells old-stocks that appears to be an old "Watchy v1.5", and sqfmi shop indeed sells only "Watchy v2.0".

Strange. I didn't see the option to purchase directly from the sqfmi shop (maybe I'm limited by my region). Forgive me as I'm new, how did you determine you had the rev v1.5 board?

My firmware says v1.3.3 in the "About Watchy" menu. Or is that something entirely different?

**Comment by PThibodeau** [comment]
> Just received my new Watchy today and I'm having the same issue out of the box. I'll try this PR change and see if it fixes my issue.

Got around to trying this fix. Battery indicator and wifi are now working in latest build on my Watchy with 2.0.2 version of esp32 board manager.

**Comment by dobrKot** [comment]
Omg, same here. Guys it's not funny.

**Pull request closed without merging**
