### PR TITLE
PCF8563: Call rtc_pcf.getDateTime in WatchyRTC::read

### LINKED ISSUE #128: Display is stuck at 00:00
The display is stuck at 00:00. 
It happened after being stuck on Bluetooth. I uploaded a watch face and new display got stuck at 00:00. 
I cannot manage to open the case to unplug the battery. How do you open the case ? Any other alternatives ? Advice ?

### PR DESCRIPTION
**Pull request by stuartpb**
Fixes #128 as noted by @neaket

### CODE REVIEW

**Comment by mrmowgli** [comment]
Totally worked on my end :+1:

**Comment by sqfmi** [comment]
Thank you!

**Comment by ITCactus** [comment]
@stuartpb could you please clarify what changes should be done (e.g. upgrade/downgrade library/dependency) to make it work/compile?

i constantly have error with this fix:
`Watchy/src/WatchyRTC.cpp:50:13: error: 'class Rtc_Pcf8563' has no member named 'getDateTime'; did you mean 'getDate'?`
in both Arduino IDE and PlatformIO.

in Arduino IDE Library Manager i see "Rtc_Pcf8563" has version "1.0.3", and it's the only version available.

**Comment by touloumtzidis** [comment]
@ITCactus Try adding https://github.com/elpaso/Rtc_Pcf8563 to lib_deps in the platformio.ini

**Pull request merged**
