### PR TITLE
Vibrate every hour on the dot

### PR DESCRIPTION
**Pull request by shtrom**
Add opion to vibrate every hour (and on reset)

Set `watchySettings.vibrateOClock` to `true` to activate.

### CODE REVIEW

**Review by sqfmi — CHANGES_REQUESTED** [review]
What is the purpose of ```alreadyVibrated``` in lines 34-40? Looks like it will make it vibrate every other hour? Or I am misunderstanding?

**Comment by shtrom** [comment]
I wasn't sure how often the RTC ticked. I guess every minutes, but maybe more often? So the `alreadyVibrated` variable ensures we only vibrate once per hour, at `currentTime.Minute == 0` , regardless of how often the RTC wakes us up in that minute.

It gets reset to `false` any time it's not `0` minutes, ready for the next hour.

**Comment by sqfmi** [comment]
The RTC should tick once per minute by default, so I think the ```currentTime.Minute == 0``` condition should trigger the vibrate once per hour, without needing ```alreadyVibrated``` (since subsequent in subsequent ticks ```currentTime.Minute``` won't be 0.

**Comment by shtrom** [comment]
This should be good now 👍🏼

**Comment by sqfmi** [comment]
Looks great, thanks!

**Pull request merged**
