### PR TITLE
StarryHorizon watch face

### PR DESCRIPTION
**Pull request by dandelany**
## Starry Horizon

My first watch face for Watchy! Randomly-generated star field background slowly rotates over the course of an hour.

image

A few questions for you in order of importance (I'm a bit of an Arduino/ESP32 noob):

1. My function for centering text doesn't seem to work very well when the string contains numbers/symbols - this causes the time to be annoyingly off-center. It appears to be an issue with the underlying `getTextBounds` function - if you uncomment line 136 in my `drawCenteredString` function, you can see the problem - it seems the bounding box is often too big. I don't think this is an issue in *your* code, but would love some help tracking down the issue and filing a minimal ticket in the correct place - presumably either with Adafruit GFX or GxEPD2?

2. It seems the watch face class, and therefore my star field, get re-instantiated every minute after wake-up. Is there any way to call `initStars` only once on first run, or are we basically starting from scratch after each deep sleep? I could probably pre-generate them and put them in PROGMEM too, but it would be nice to be able to tweak the parameters.

3. Is there any benefit or preference re: putting things in multiple files vs one file? And my file is a `.ino` while others are `.cpp`/`.h` - is that OK?

### CODE REVIEW

**Comment by sqfmi** [comment]
This is awesome, thanks for the PR!

1. Let us look into this and test it out as well, we suspect it might also have to do with how the font file is converted and the size of each character.

2. Saving it in PROGMEM flash might be the way to go, it's also possible to store the stars array in RTC memory so it's preserved between wake/sleep cycles, but that depends on the size of the array.

3. ```.ino``` and all in one file is perfect, if the watch face gets complicated with a few hundred lines then it might be good to separate the files.

**Comment by dandelany** [comment]
I was able to work around # 1 by setting the text wrap option to `false` - the issue seems related to text wrapping. I will push a new version with that + a few other improvements tonight when I have time to clean it up.

**Comment by dandelany** [comment]
Pushed a few more changes:
* Set text wrap to `false` which fixes the centered text issue. Would still be nice to figure out the source of this issue someday, so that wrapping + text bounds can be used reliably together. FWIW when text wrap is `true`, it seems like the bounding box "thinks" the text wraps to two lines before it actually does - eg. the string "1111" fits on one line (using my custom font), but the bounding box is two characters tall. Will look into it more some other day...
* Stored star locations in PROGMEM so they're not being re-generated every minute
* Added vertical grid lines, rounded horizon, moved date display

I now consider this "done", unless you have any other recommended improvements :)

**Comment by sqfmi** [comment]
Wow, that looks rad! Definitely gonna to sport this watch face on my own Watchy!

**Pull request merged**
